apiVersion: apps/v1
kind: Deployment
metadata:
  name: guests-welcome
  labels:
    app: guests-welcome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guests-welcome
  template:
    metadata:
      labels:
        app: guests-welcome
    spec:
      containers:
      - name: guests-welcome
        image: python:3.11-slim
        command: ["python3", "app.py"]
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: guests-welcome-service
spec:
  selector:
    app: guests-welcome
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort
